<?php
/**
 * Cette classe va servir de modele pour les classes "Commentaires" et "SousCommentaires"
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

abstract class Commentaire {

	/**
	 * Code Identifiant d'un commentaire ou sous-commentaire
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * Attribut pseudo présent à la fois dans Commentaires et dans Sous-Commentaires
	 * @var string
	 * @access protected
	 */
	protected  $pseudo;

	/**
	 * Idem que pour pseudo
	 * @var string
	 * @access protected
	 */
	protected  $message;

	/**
	 * Idem que pour Pseudo
	 * @var date
	 * @access protected
	 */
	protected  $dateCreat;


}
?>