<?php
/**
 * Classe permettant de gérer les commentaires
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class CommentsManager {

	/**
	 *
	 * @var PDO
	 * @access protected
	 */
	protected  $db;


	/**
	 * @access public
	 * @param PDO $db
	 * @return void
	 */

	public function __construct(PDO $db) {

	}


	/**
	 * @access public
	 * @param Commentaire $comm
	 * @return void
	 */

	public function create(Commentaire $comm) {

	}


	/**
	 * @access public
	 * @param int $id
	 * @return Commentaire
	 */

	public function read($id) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public function readList() {

	}


	/**
	 * @access public
	 * @param Personnage $perso
	 * @return void
	 */

	public function update(Commentaire $comm) {

	}


	/**
	 * @access public
	 * @param Personnage $perso
	 * @return void
	 */

	public function delete(Commentaire $comm) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public function count() {

	}


	/**
	 * @access public
	 * @param int|string $info
	 * @return bool
	 */

	public function exists(int|string $info) {

	}


}
?>
