<?php
/**
 * Cette classe correspond à la table Commentaires dans la BDD
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 * @see        Commentaire
 */
require_once('Commentaire.php');

class Comments extends Commentaire {

	/**
	 * Identifiant de l'episode afin de pouvoir le lier à la classe episode
	 * @var int
	 * @access protected
	 */
	protected  $epid;


}
?>
