<?php
/**
 * Classe permettant de gérer les episodes
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class EpisodesManager {

	/**
	 *
	 * @var PDO
	 * @access protected
	 */
	protected  $db;


	/**
	 * @access public
	 * @param PDO $db
	 * @return void
	 */

	public function __construct(PDO $db) {

	}


	/**
	 * @access public
	 * @param Episode $epis
	 * @return void
	 */

	public function create(Episode $epis) {

	}


	/**
	 * @access public
	 * @param int $id
	 * @return Episode
	 */

	public function read($id) {

	}


	/**
	 * @access public
	 * @return array
	 */

	public function readList() {

	}


	/**
	 * @access public
	 * @param Episode $epis
	 * @return void
	 */

	public function update(Episode $epis) {

	}


	/**
	 * @access public
	 * @param Episode $epis
	 * @return void
	 */

	public function delete(Episode $epis) {

	}


	/**
	 * @access public
	 * @return int
	 */

	public function count() {

	}


	/**
	 * @access public
	 * @param int|string $info
	 * @return bool
	 */

	public function exists(int|string $info) {

	}


}
?>
