<?php
/**
 * Cette classe correspond à la table episodes de la BDD
 * Code skeleton generated by dia-uml2php5 plugin
 * written by KDO kdo@zpmag.com
 */

class Episodes {

	/**
	 * Correspond à l'identifant de l'episode
	 * @var int
	 * @access protected
	 */
	protected  $id;

	/**
	 * Correspond au titre de l'episode
	 * @var string
	 * @access protected
	 */
	protected  $titre;

	/**
	 * Correspond au contenu de l'episode	
	 * @var text
	 * @access protected
	 */
	protected  $contenu;

	/**
	 * Date de création de l'episode
	 * @var date
	 * @access protected
	 */
	protected  $dateCrea;

	/**
	 * Date de modification de l'episode
	 * @var date
	 * @access protected
	 */
	protected  $dateModif;

	/**
	 * Attribut contenant des valeurs :
0 = Episode peut être modifié et supprimé
1 = Episode validé donc les options de modification et de suppression sont désactivés
	 * @var int
	 * @access protected
	 */
	protected  $valided = 0;


	/**
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public  function __construct($donnees) {

	}


	/**
	 * @access public
	 * @param array $donnees 
	 * @return void
	 */

	public  function hydrate($donnees) {

	}


}
?>